### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by rsev27** [redmalmon/philippine-address-selector#1]
Good day, ask ko lang po kung paano i set yung value ng select box from database. salamat po

**Comment by wilfredpine** [comment]
Good day po, check nyo sir yung mismong code. inupdate ko na po sya, meron
po dun na nakahidden na input(textbox) , dun po napupunta value ng address.
yun po ang gagamitin para isave sa database. Kasi pag select input ang
ginamit ay ang value nun ay ID nung address.

Di ko lang po na update yung ReadMe file

**Comment by rsev27** [comment]
ok po salamat po
